#!/usr/bin/env node
// Builds the embedded HVAC knowledge base module consumed by the Wasp app.
//
// Source of truth: <repo>/data/hvac-knowledge/**/*.md and <repo>/skills/*.md (human-edited).
// Output (generated, do not hand-edit): template/app/src/hvac-assistant/knowledgeData.ts
//
// Why embed instead of reading from disk at runtime: Wasp bundles server operations,
// so a generated TS module is the most portable way to ship the KB with the deploy.
//
// Run from the repo root:  node tools/build-hvac-kb.mjs

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const KB_DIR = join(repoRoot, "data", "hvac-knowledge");
const SKILLS_DIR = join(repoRoot, "skills");
const OUT = join(
  repoRoot,
  "template",
  "app",
  "src",
  "hvac-assistant",
  "knowledgeData.ts",
);

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (name.endsWith(".md")) out.push(full);
  }
  return out;
}

function collect(dir, baseForId) {
  return walk(dir)
    .sort()
    .map((full) => ({
      id: relative(baseForId, full).split("\\").join("/"),
      content: readFileSync(full, "utf8"),
    }));
}

// Knowledge docs are cited by "<folder>/<file>.md" (relative to data/hvac-knowledge),
// which matches the [Source: ...] convention used throughout the skills.
const docs = collect(KB_DIR, KB_DIR).filter((d) => d.id !== "README.md");
const skills = collect(SKILLS_DIR, SKILLS_DIR).filter((s) => s.id !== "README.md");

const banner = `// AUTO-GENERATED by tools/build-hvac-kb.mjs — do not edit by hand.
// Edit the markdown in data/hvac-knowledge/ or skills/ and re-run the generator.
// Generated: ${new Date().toISOString()}
`;

const body = `${banner}
export interface KnowledgeDoc {
  /** Citation id relative to data/hvac-knowledge, e.g. "pricing/ac-repair-2024.md". */
  id: string;
  content: string;
}

export interface SkillDoc {
  /** File name, e.g. "hvac-ai-receptionist.md". */
  id: string;
  content: string;
}

export const knowledgeDocs: KnowledgeDoc[] = ${JSON.stringify(docs, null, 2)};

export const skillDocs: SkillDoc[] = ${JSON.stringify(skills, null, 2)};
`;

writeFileSync(OUT, body);
console.log(
  `Wrote ${OUT}\n  ${docs.length} knowledge docs, ${skills.length} skills.`,
);
